version: '3'
services:
  phunkis-service:
    image: dsek/phunkis-service:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      JDBC_URL: jdbc:mysql://db/phunkis
  db:
    image: mysql/mysql-server:8.0
    ports:
      - "3306"
    environment:
      MYSQL_DATABASE: phunkis
      MYSQL_USER: testuser
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - "./database_init/:/docker-entrypoint-initdb.d/:ro"
  gateway:
    image: dsek/gateway:latest
    ports:
      - "8083:8083"
    depends_on:
      - phunkis-service
      - login
      - hoarder-service
    restart: unless-stopped
    build:
      context: .
    environment:
      - LOGIN_URL=http://login:1338/graphql
      - ROLE_URL=http://phunkis-service:8080/roles
      - ROLE_INSTANCE_URL=http://phunkis-service:8080/roleInstances
      - HOARDER_URL=http://hoarder-service:8082/graphql
  login:
    image: dsek/login-service:latest
    ports:
        - "1338:1338"
    volumes:
      - "./keys/:/keys/:ro"
    environment:
        NODE_ENV: development
  hoarder-service:
    image: dsek/hoarder:latest
    ports:
        - "8082:8082"
    depends_on:
      - neo4j
    environment:
      NEO4J_HOST: neo4j
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: password
      RUN_STARTUP_SCRIPTS: "false"
      NODE_ENV: development
      DEBUG: neo4j-graphql-js
    volumes:
      - "./database_init/:/startup-scripts/:ro"
    build:
        context: ../hoarDer
  neo4j:
    image: neo4j:3.5
    ports:
        - "7474:7474"
        - "7473:7473"
        - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - "./db/data/:/data/:rw"
      - "./db/logs/:/logs/:rw"
      - "./plugins/:/plugins/:ro"
      - "./db_import/:/var/lib/neo4j/import/:ro"
